# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rock/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rock)

$(call add-radio-file-sha1-checked,radio/dpm.img,ac85f26e24ad75a0b3295db26ed898bedfa7d80a)
$(call add-radio-file-sha1-checked,radio/gz.img,bb10a0d1811d755cf9857095777ebe45d422934a)
$(call add-radio-file-sha1-checked,radio/lk.img,7b9795f298d59609e128faa505ad5f2a80d156c1)
$(call add-radio-file-sha1-checked,radio/logo.img,acb72767ada0d028e62eda3254ce1c864ac59f78)
$(call add-radio-file-sha1-checked,radio/mcupm.img,b3a126a298fc4bddec7c40b4de1406947e4d59fe)
$(call add-radio-file-sha1-checked,radio/md1img.img,05a779c755dbd07d3e5a20a72c5aa9d0cb259c5d)
$(call add-radio-file-sha1-checked,radio/pi_img.img,74acb14e14290c081e76b3a17072531412b35315)
#$(call add-radio-file-sha1-checked,radio/preloader_raw.img,7b98750858165a58ebfa65bfe7c01112c5198efd)
$(call add-radio-file-sha1-checked,radio/scp.img,8a8c6c5cb965eee8eddf4adee3cfae8912f5a4d9)
$(call add-radio-file-sha1-checked,radio/spmfw.img,ed39ff4266da482f75dc9610c015adde0724dab3)
$(call add-radio-file-sha1-checked,radio/sspm.img,1a4006e82056970ea15f1fe4cd484f05408ef56e)
$(call add-radio-file-sha1-checked,radio/tee.img,e28b38203acce8c51575d9dd02f0c50c354989ff)

endif
