# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rock/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rock)

$(call add-radio-file,radio/dpm.img)
$(call add-radio-file,radio/gz.img)
$(call add-radio-file,radio/lk.img)
$(call add-radio-file,radio/logo.img)
$(call add-radio-file,radio/mcupm.img)
$(call add-radio-file,radio/md1img.img)
$(call add-radio-file,radio/pi_img.img)
$(call add-radio-file,radio/preloader_raw.img)
$(call add-radio-file,radio/scp.img)
$(call add-radio-file,radio/spmfw.img)
$(call add-radio-file,radio/sspm.img)
$(call add-radio-file,radio/tee.img)

endif
